/* Run this on sandbar_user */

CREATE OR REPLACE SYNONYM AREA_VOLUME_CALC FOR SANDBAR.AREA_VOLUME_CALC;


CREATE OR REPLACE SYNONYM DJANGO_FLATPAGE FOR SANDBAR.DJANGO_FLATPAGE;


CREATE OR REPLACE SYNONYM DJANGO_FLATPAGE_SITES FOR SANDBAR.DJANGO_FLATPAGE_SITES;


CREATE OR REPLACE SYNONYM DJANGO_SITE FOR SANDBAR.DJANGO_SITE;


CREATE OR REPLACE SYNONYM GET_AREA_VOL_TF FOR SANDBAR.GET_AREA_VOL_TF;


CREATE OR REPLACE SYNONYM SB_CALCS FOR SANDBAR.SB_CALCS;


CREATE OR REPLACE SYNONYM SITES FOR SANDBAR.SITES;


CREATE OR REPLACE SYNONYM SITE_PHOTOS FOR SANDBAR.SITE_PHOTOS;


CREATE OR REPLACE SYNONYM SITE_SANDBAR_REL FOR SANDBAR.SITE_SANDBAR_REL;


CREATE OR REPLACE SYNONYM SURVEYS FOR SANDBAR.SURVEYS;
